# Default Egress Policy Template
# Configurable "never reveal X" templates for content filtering

policy:
  id: "default_strict"
  name: "Default Strict Policy"
  tenant: "system"
  description: "Default policy with strict PII and secret detection"

  # Never reveal these content types
  never_reveal:
    - "password"
    - "private_key"
    - "ssn"
    - "credit_card"
    - "api_key"
    - "jwt_token"
    - "database_connection_string"
    - "aws_access_key"
    - "azure_key"
    - "gcp_service_account"

  # Detection settings
  pii_detection:
    enabled: true
    confidence_threshold: 0.95
    categories:
      - "personal"
      - "financial"
      - "medical"
      - "government"
      - "other"

  secret_detection:
    enabled: true
    confidence_threshold: 0.90
    types:
      - "api_key"
      - "password"
      - "token"
      - "private_key"
      - "connection_string"
      - "other"

  near_dup_detection:
    enabled: true
    similarity_threshold: 0.8
    max_stored_hashes: 10000

  # Content processing
  redaction_mode: "mask" # mask, hash, remove
  max_content_length: 1000000 # 1MB
  preserve_formatting: true

  # Performance settings
  processing_timeout_ms: 5000
  cache_enabled: true
  cache_ttl_seconds: 3600

  # Audit settings
  log_redactions: true
  log_processing_times: true
  log_policy_violations: true

  # Compliance
  gdpr_compliant: true
  hipaa_compliant: false
  sox_compliant: true

  created_at: "2024-01-01T00:00:00Z"
  updated_at: "2024-01-01T00:00:00Z"
  version: "1.0.0"
