apiVersion: v1
kind: Config
clusters:
- name: local-cluster
  cluster:
    server: http://localhost:8001
    insecure-skip-tls-verify: true
contexts:
- name: local-context
  context:
    cluster: local-cluster
    user: local-user
current-context: local-context
users:
- name: local-user
  user:
    token: ""
