# Accuracy Monitoring Configuration

confidence_thresholds:
  high: 0.8
  medium: 0.6
  low: 0.4
  critical: 0.2

fallback_policies:
  low_confidence:
    threshold: 0.6
    action: "human_review"
    priority: 1
    parameters:
      review_timeout_hours: 24
      escalation_threshold: 0.3
      auto_approval: false

  source_unavailable:
    action: "alternative_model"
    priority: 2
    parameters:
      retry_count: 3
      model_fallback_chain: ["gpt-4", "gpt-3.5-turbo", "claude-3"]
      confidence_boost: 0.1

  verification_failed:
    action: "cached_response"
    priority: 3
    parameters:
      cache_ttl_hours: 168  # 1 week
      similarity_threshold: 0.8
      max_cache_age_days: 30

  critical_failure:
    action: "error_response"
    priority: 4
    parameters:
      error_message: "Unable to provide accurate response at this time"
      retry_after_minutes: 15
      escalation_required: true

kpi_weights:
  confidence_score: 0.3
  source_verification: 0.3
  fallback_effectiveness: 0.2
  response_quality: 0.2

monitoring:
  metrics_collection_interval: 10  # seconds
  kpi_update_interval: 60  # seconds
  alert_thresholds:
    confidence_drop: 0.1
    verification_failure_rate: 0.05
    fallback_activation_rate: 0.2

verification:
  source_types:
    - "document"
    - "database"
    - "api"
    - "knowledge_base"
    - "web_search"
    - "internal_kb"
  
  verification_methods:
    - "content_hash_validation"
    - "relevance_scoring"
    - "source_authenticity"
    - "timestamp_validation"
    - "metadata_consistency"

fallback_escalation:
  levels:
    - level: 1
      action: "retry_with_backoff"
      max_retries: 3
      backoff_seconds: 5
    
    - level: 2
      action: "alternative_model"
      max_attempts: 2
      timeout_seconds: 30
    
    - level: 3
      action: "human_review"
      max_wait_hours: 4
      auto_escalate: true
    
    - level: 4
      action: "error_response"
      notify_ops: true
      incident_creation: true

quality_assessment:
  factors:
    - name: "confidence_score"
      weight: 0.4
      threshold: 0.7
    
    - name: "source_verification"
      weight: 0.3
      threshold: 0.9
    
    - name: "response_completeness"
      weight: 0.2
      threshold: 0.8
    
    - name: "processing_efficiency"
      weight: 0.1
      threshold: 0.6

reporting:
  formats:
    - "json"
    - "csv"
    - "pdf"
    - "html"
  
  retention:
    raw_data_days: 90
    aggregated_data_days: 365
    kpi_history_days: 730
  
  export_schedules:
    - frequency: "daily"
      format: "csv"
      include_kpis: true
    
    - frequency: "weekly"
      format: "pdf"
      include_trends: true
    
    - frequency: "monthly"
      format: "html"
      include_detailed_analysis: true

alerts:
  channels:
    - type: "email"
      recipients: ["ops@company.com", "ai-team@company.com"]
      frequency: "immediate"
    
    - type: "slack"
      channel: "#ai-monitoring"
      frequency: "immediate"
    
    - type: "pagerduty"
      service: "ai-accuracy"
      urgency: "high"
  
  conditions:
    - name: "confidence_threshold_breach"
      metric: "average_confidence"
      operator: "<"
      threshold: 0.6
      duration_minutes: 15
    
    - name: "fallback_rate_spike"
      metric: "fallback_activation_rate"
      operator: ">"
      threshold: 0.3
      duration_minutes: 10
    
    - name: "verification_failure_increase"
      metric: "source_verification_failure_rate"
      operator: ">"
      threshold: 0.1
      duration_minutes: 30
