name: Verify PF
on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}
          fetch-depth: 0
      - run: make verify # your PF verification entrypoint
